sudo: required

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f32286c047612bea82b0
    on_success: always  # options: [always|never|change] default: change
    on_failure: always  # options: [always|never|change] default: always
    on_start: never    # options: [always|never|change] default: never

services:
  - docker

before_install:
  - docker pull klaemo/couchdb:1.6.1
  - docker run -d -p 5984:5984 --name bell klaemo/couchdb
  - echo "node_modules/.bin/couchapp push \$1 \$2" > pushDocToDb.sh
  - chmod +x node_modules/.bin/couchapp pushDocToDb.sh
  - cp install_windows install_linux
  - sed -i "s#pushDocToDb.bat#./pushDocToDb.sh#" install_linux
  - sed -i 's#databases\\\\\\\\#databases/#' install_linux
  - sed -i 's#databases\\\\\\#databases/#' install_linux
  - sed -i 's#databases\\\\#databases/#' install_linux
  - sed -i 's/NationBell/nation/' init_docs/ConfigurationsDoc-Nation.txt
  - sed -i 's/nationbell/NATION/' init_docs/ConfigurationsDoc-Nation.txt
  - sed -i 's#Male#Female#' install_linux
  - sed -i 's#somalia#nation#' install_linux
  - while ! curl -X GET http://127.0.0.1:5984/_all_dbs ; do sleep 1; done
  - node install_linux http://127.0.0.1:5984
  - curl -X PUT 'http://127.0.0.1:5984/_config/log/file' -d '"/usr/local/var/log/couchdb/couch.log"'
  - curl -X PUT 'http://127.0.0.1:5984/_config/httpd/allow_jsonp' -d '"true"'
  - curl -X PUT 'http://127.0.0.1:5984/_config/admins/nation' -d '"oleoleole"'

script:
  - docker ps -a | grep bell
  - curl -X GET http://127.0.0.1:5984/_all_dbs
  - i=$(curl -X GET http://127.0.0.1:5984/_all_dbs | jq length); if [ $i -ne 36 ]; then exit 1; fi
